name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Prepack from TypeScript/ES6 source
      run: yarn prepack
    - name: Launch tests
      run: yarn test
  live-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install excalidraw-cli
      run: sudo yarn global add excalidraw-cli
    - name: Prepare test environment
      run: mkdir -p foo/bar
    - name: Test 1
      run: excalidraw-cli .github/assets/ foo
    - name: Test 2
      run: excalidraw-cli .github/assets/ ./foo/bar
    - name: Test 3
      run: excalidraw-cli .github/assets/ foo/bar
