name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Prepack from TypeScript/ES6 source
      run: yarn prepack
    - name: Launch tests
      run: yarn test
    - name: Prepare live-test environment
      run: mkdir -p foo/bar
    - name: Test 1
      run: yarn excalidraw-cli .github/assets/
    - name: Test 2
      run: yarn excalidraw-cli .github/assets/ foo
    - name: Test 3
      run: yarn excalidraw-cli .github/assets/ ./foo/bar
    - name: Test 4
      run: yarn excalidraw-cli .github/assets/ foo/bar
